services:
  mysql-farmacia:  # <-- Nombre del servicio
    image: mysql:8.0.42
    container_name: mysql-farmacia
    restart: unless-stopped
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sistemastock
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb/:/docker-entrypoint-initdb.d  # <- Carpeta local mapeada
    networks:
      - backend-network

  backend:  # Servicio para NestJS
    container_name: backend-farmacia
    build: ./backend  # Ruta a tu Dockerfile del backend
    ports:
      - "3000:3000"  # Mapeo de puertos (host:container)
    volumes:
      - ./backend:/app  # Monta el código fuente (para desarrollo)
      - /app/node_modules  # Excluye node_modules del volumen
    environment:
      NODE_ENV: test   # antes development
    command: npm run start:dev  # comando de inicio
    depends_on:
      - mysql-farmacia  # Espera a que MySQL esté listo    
    networks:
      - backend-network

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge
